### ISSUE TITLE
Rust CI Improvement

### ISSUE THREAD

**Issue by Confucian-e** [Confucian-e/stormint#5]
Using cache to speed up.

```yaml
name: Rust CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      # Add cache for fmt job
      - uses: Swatinem/rust-cache@v2
      - name: Run Format
        run: cargo fmt --all -- --check

  clippy:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-Dwarnings"
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      # Add cache for clippy job
      - uses: Swatinem/rust-cache@v2
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      # Add cache for build job
      - uses: Swatinem/rust-cache@v2
        with:
          # Optionally specify cache prefix if you have multiple Rust projects
          # cache-prefix: "my-project"
          
          # Optionally specify additional directories to cache
          cache-directories: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
```
